### PR TITLE
Make centroid offset for low separations optional

### PR DESCRIPTION
**Pull request by jakeown**

### CODE REVIEW

**Comment by jakeown** [comment]
Centroid offset optional

**Review by mcyc — DISMISSED** [review]

**Review by low-sky — APPROVED** [review]

**Comment by low-sky** [comment]
Good to go?

**Comment by mcyc** [comment]
Functionally, I think so. Perhaps make outputting (2,2) lines optional?

I have plans to modularize the code and enable multi-processing, as I did with my own version of the code, but that is not necessary for our test.

**Comment by low-sky** [comment]
Yes; I'm seeing that we're overloading this script with a lot of use cases, which are obviating the main purpose of providing a common set of tests.  Factoring out the cube generation and having a set of routines that call pieces of this code seems like it would be preferred over putting everything in one script.

**Comment by mcyc** [comment]
Agreed, that's what I have in mind as well.

**Comment by mcyc** [comment]
Let's merge the pull request first. I can start modularizing the code following that.

**Pull request merged**
